Fixed random sample image URI
Summary:
The old version caused some invalid images, resulting in errors, which makes debugging harder.
Example error:
```
2020-02-21 13:35:29.771 21185-21390/com.facebook.fresco.samples.showcase W/unknown:RequestLoggingListener: time 356359026: onProducerFinishWithFailure: {requestId: 344, stage: BitmapMemoryCacheKeyMultiplexProducer, elapsedTime: 97 ms, extraMap: null, throwable: java.io.IOException: Unexpected HTTP code Response{protocol=h2, code=404, message=, url=https://picsum.photos/400/400?image=105}}
    java.io.IOException: Unexpected HTTP code Response{protocol=h2, code=404, message=, url=https://picsum.photos/400/400?image=105}
        at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:166)
```

Reviewed By: wizh

Differential Revision: D20030225

fbshipit-source-id: 1f0fa054013fba17fdc7709983bfaba4046b0a5a