Fix NDK setting for ndk ver < 17
Summary: Changes in github 1b86b49f60861b56d7bd89550e16f7f8e5b69383  introduced the following error for ndk < 17: `fresco/static-webp/src/main/jni/static-webp/../../../../nativedeps/merge/libwebp-0.6.1/src/dsp/yuv.c:104: undefined reference to 'WebPInitSamplersMIPS32'`

Reviewed By: oprisnik

Differential Revision: D8723530

fbshipit-source-id: e9167b7e5221493ddb09546a0482f79e3b75c2dc