Do not run ProgressiveDecoder for non-jpeg (fix webp)
Summary:
Currently, the `DecodeProducer` will run `ProgressiveDecodeProducer` regardless of the image type. That caused images like WebP not to load at all if their intermediate decoding would throw an error.

**Test Plan**

Before this change, one could observe the following errors (amongst other most likely) in the showcase app on Android 4.4.2

```
02-01 11:44:12.940 4065-4087/com.facebook.fresco.samples.showcase W/unknown:RequestLoggingListener: time 4014794: onProducerFinishWithFailure: {requestId: 17, stage: DecodeProducer, elapsedTime: 0 ms, extraMap: {encodedImageSize=300x225, imageFormat=WEBP_ANIMATED, sampleSize=1, hasGoodQuality=true, requestedImageSize=unknown, queueTime=0, isFinal=false}, throwable: java.lang.IllegalArgumentException: Failed to create demuxer}
                                                                                                    java.lang.IllegalArgumentException: Failed to create demuxer
                                                                                                        at com.facebook.animated.webp.WebPImage.nativeCreateFromNativeMemory(Native Method)
                                                                                                        at com.facebook.animated.webp.WebPImage.create(WebPImage.java:82)
                                                                                                        at com.facebook.animated.webp.WebPImage.decode(WebPImage.java:87)
                                                                                                        at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeWebP(AnimatedImageFactoryImpl.java:112)
                                                                                                        at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$2.decode(AnimatedFactoryV2Impl.java:102)
                                                                                                        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeAnimatedWebp(DefaultImageDecoder.java:202)
                                                                                                        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:62)
                                                                                                        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:121)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:251)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300(DecodeProducer.java:115)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:154)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:204)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:24)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:75)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53)
                                                                                                        at java.lang.Thread.run(Thread.java:841)
```

and

```
02-01 11:44:12.820 4065-4086/com.facebook.fresco.samples.showcase W/unknown:RequestLoggingListener: time 4014678: onProducerFinishWithFailure: {requestId: 15, stage: DecodeProducer, elapsedTime: 0 ms, extraMap: {encodedImageSize=550x404, imageFormat=WEBP_SIMPLE, sampleSize=1, hasGoodQuality=true, requestedImageSize=unknown, queueTime=1, isFinal=false}, throwable: java.lang.RuntimeException: Failed to pin Bitmap}
                                                                                                    java.lang.RuntimeException: Failed to pin Bitmap
                                                                                                        at com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap(Native Method)
                                                                                                        at com.facebook.imagepipeline.nativecode.Bitmaps.pinBitmap(Bitmaps.java:41)
                                                                                                        at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.pinBitmap(DalvikPurgeableDecoder.java:160)
                                                                                                        at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap(KitKatPurgeableDecoder.java:30)
                                                                                                        at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeFromEncodedImage(DalvikPurgeableDecoder.java:64)
                                                                                                        at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeFromEncodedImage(KitKatPurgeableDecoder.java:30)
                                                                                                        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeStaticImage(DefaultImageDecoder.java:149)
                                                                                                        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:66)
                                                                                                        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:121)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:251)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300(DecodeProducer.java:115)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:154)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:204)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:24)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:75)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53)
                                                                                                        at java.lang.Thread.run(Thread.java:841)
```

When loaded locally (or from cache), the image would appear correctly.

After the change, all WebP load correctly - even if they are loaded "progressively" from the network.

Reviewed By: oprisnik

Differential Revision: D6870871

fbshipit-source-id: 8134499f07037365ae18c5a1489e2fa023319a7b