Convert the CircleCI workflow to a GitHub Actions workflow (#2762)
Summary:
This pull request converts the CircleCI workflows to GitHub actions workflows. [Github Actions Importer](https://github.com/github/gh-actions-importer) was used to convert the workflows initially, then I edited them manually to correct errors in translation.

**Issues**

1. _facebook/fresco/build -> Run Tests_

```
Execution failed for task ':animated-base:testDebugUnitTest'.
```

<details>
<summary style="list-style-type: none;">Full Error</summary>
<pre>
com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose_whenCloseableStaticBitmapNull_thenReturnNull FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40

com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose_whenBitmapReferenceInvalid_thenReturnReference FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40

com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40

com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose_whenBitmapRecycled_thenReturnReference FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40

com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose_whenImageReferenceInvalid_thenReturnNull FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40

com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose_whenInputNull_thenReturnNull FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40

com.facebook.fresco.animation.bitmap.cache.FrescoFrameCacheTest > testExtractAndClose_whenCloseableStaticBitmapClosed_thenReturnNull FAILED
    org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
        Caused by: org.mockito.exceptions.base.MockitoException at FrescoFrameCacheTest.java:40
            Caused by: java.lang.IllegalStateException at FrescoFrameCacheTest.java:40
                Caused by: java.lang.IllegalArgumentException at FrescoFrameCacheTest.java:40
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRendererTest > testRenderFrameUnsuccessful FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedDrawableBackendFrameRendererTest.java:104
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedDrawableBackendFrameRendererTest.java:104
            Caused by: java.lang.IllegalStateException at AnimatedDrawableBackendFrameRendererTest.java:104
                Caused by: java.lang.IllegalArgumentException at AnimatedDrawableBackendFrameRendererTest.java:104

com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRendererTest > testSetBounds FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedDrawableBackendFrameRendererTest.java:52
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedDrawableBackendFrameRendererTest.java:52
            Caused by: java.lang.IllegalStateException at AnimatedDrawableBackendFrameRendererTest.java:52
                Caused by: java.lang.IllegalArgumentException at AnimatedDrawableBackendFrameRendererTest.java:52

com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRendererTest > testRenderFrame FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedDrawableBackendFrameRendererTest.java:104
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedDrawableBackendFrameRendererTest.java:104
            Caused by: java.lang.IllegalStateException at AnimatedDrawableBackendFrameRendererTest.java:104
                Caused by: java.lang.IllegalArgumentException at AnimatedDrawableBackendFrameRendererTest.java:104

com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImplTest > testOffsets FAILED
    java.lang.RuntimeException at AbstractClassloaderExecutor.java:108
        Caused by: java.lang.reflect.InvocationTargetException at DirectConstructorHandleAccessor.java:79
            Caused by: java.lang.ExceptionInInitializerError at XStream.java:989
                Caused by: java.lang.reflect.InaccessibleObjectException at AccessibleObject.java:354

com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImplTest > testNoUpscaling FAILED
    java.lang.RuntimeException at AbstractClassloaderExecutor.java:108
        Caused by: java.lang.reflect.InvocationTargetException at DirectConstructorHandleAccessor.java:79
            Caused by: java.lang.NoClassDefFoundError at XStream.java:989
                Caused by: java.lang.ExceptionInInitializerError at AccessibleObject.java:354

com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImplTest > testNarrow FAILED
    java.lang.RuntimeException at AbstractClassloaderExecutor.java:108
        Caused by: java.lang.reflect.InvocationTargetException at DirectConstructorHandleAccessor.java:79
            Caused by: java.lang.NoClassDefFoundError at XStream.java:989
                Caused by: java.lang.ExceptionInInitializerError at AccessibleObject.java:354

com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImplTest > testSimple FAILED
    java.lang.RuntimeException at AbstractClassloaderExecutor.java:108
        Caused by: java.lang.reflect.InvocationTargetException at DirectConstructorHandleAccessor.java:79
            Caused by: java.lang.NoClassDefFoundError at XStream.java:989
                Caused by: java.lang.ExceptionInInitializerError at AccessibleObject.java:354

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testContainsFullReuseFlowWithMultipleItems FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testBasic FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testReuse FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testCantReuseIfNotClosed FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testStillThereIfClosed FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testMultipleFrames FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testContains FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testReplace FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.animated.impl.AnimatedFrameCacheTest > testContainsWhenReused FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedFrameCacheTest.java:53
            Caused by: java.lang.IllegalStateException at AnimatedFrameCacheTest.java:53
                Caused by: java.lang.IllegalArgumentException at AnimatedFrameCacheTest.java:53

com.facebook.imagepipeline.producers.AnimatedRepeatedPostprocessorProducerTest > testNonStaticBitmapIsPassedOn FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedRepeatedPostprocessorProducerTest.java:76
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedRepeatedPostprocessorProducerTest.java:76
            Caused by: java.lang.IllegalStateException at AnimatedRepeatedPostprocessorProducerTest.java:76
                Caused by: java.lang.IllegalArgumentException at AnimatedRepeatedPostprocessorProducerTest.java:76

com.facebook.imagepipeline.producers.AnimatedSingleUsePostprocessorProducerTest > testNonStaticBitmapIsPassedOn FAILED
    org.mockito.exceptions.base.MockitoException at AnimatedSingleUsePostprocessorProducerTest.java:69
        Caused by: org.mockito.exceptions.base.MockitoException at AnimatedSingleUsePostprocessorProducerTest.java:69
            Caused by: java.lang.IllegalStateException at AnimatedSingleUsePostprocessorProducerTest.java:69
                Caused by: java.lang.IllegalArgumentException at AnimatedSingleUsePostprocessorProducerTest.java:69

35 tests completed, 25 failed

> Task :animated-base:testDebugUnitTest FAILED
454 actionable tasks: 454 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':animated-base:testDebugUnitTest'.
</pre>
</details>

## How did you test this change?

I tested these changes in a [forked repo](https://github.com/robandpdx-org/fresco/actions/runs/8024468495).

https://fburl.com/workplace/f6mz6tmw

Pull Request resolved: https://github.com/facebook/fresco/pull/2762

Reviewed By: kartavya-ramnani

Differential Revision: D56526799

Pulled By: steelrooter

fbshipit-source-id: 500220691ddcdd0532d9db828474f51d7d4c3f6d